#!/bin/bash

if [ -d ~/lds ]
then
rm -rf ~/lds
fi
mkdir ~/lds
cp -r ./bin ~/lds/

HOME=`echo ~`
BIN_DIR="$HOME/lds/bin"
BASH_PROFILE=".bashrc"

if [[ `uname -s` == *"Darwin"* ]]
then 
BASH_PROFILE='.bash_profile'
fi

if [[ "$PATH" == *$BIN_DIR* ]]
then 
	echo "Path already added!! Skipping!"
	exit
fi

echo ''  >> "$HOME/$BASH_PROFILE"
echo '#for Lazy Developer Script'  >> "$HOME/$BASH_PROFILE"
echo "export PATH=$BIN_DIR:"'$PATH'  >> "$HOME/$BASH_PROFILE"

echo "Installed..." 
