#!/bin/bash

#checking if current directory is lds or not
CURR_DIR=${PWD##*/}
if [ $CURR_DIR != "lds" ]; then
	echo "Wrong directory! Run from within the lds directory"
	exit
fi

#moving new binaries to home location (installation)
if [ -d ~/.lds ]
then
  chmod -R a+wX ~/.lds
	rm -rf ~/.lds
fi

cp -r . ~/.lds
chmod -R a-wX ~/.lds
#setting variables
BIN_DIR="$HOME/.lds/bin"
BASH_PROFILE=".bashrc"

#checking whether the system is Linux or macOs which 
#will change the name of the bash file
if [[ `uname -s` == *"Darwin"* ]]
then 
	BASH_PROFILE='.bash_profile'
fi

#Adding commands to the bash_profile (currently a temp file)
echo ''  > /tmp/ENV_VAR_LDS
echo '#for Lazy Developer Script'  >> /tmp/ENV_VAR_LDS
echo "export PATH=$BIN_DIR:"'$PATH'  >> /tmp/ENV_VAR_LDS


#Asking user whether to install tellmyip or not
INSTALL_tellmyip="n"
echo "Do you want to autorun tellmyip whenever the wirless interface is up?? (y/n) (Default: No): "
read INSTALL_tellmyip

if [[ "$INSTALL_tellmyip" == "y" || "$INSTALL_tellmyip" == "Y" || "$INSTALL_tellmyip" == "yes" ]]
then
  #for running tellmyip everytime a connection is setup
  #getting config variables
  source ./config
  echo -n "$PASSWORD_LDS" | sudo -S cp "$BIN_DIR/tellmyip" /etc/network/if-up.d/
fi

#checking whether the path is already added to profile
#to avoid rewriting it
if [[ "$PATH" == *$BIN_DIR* ]]
then 
	echo "Path already added!! Skipping!"
	echo "Make sure the following lines are in $HOME/$BASH_PROFILE"
	cat /tmp/ENV_VAR_LDS
	rm /tmp/ENV_VAR_LDS
	exit
fi

cat /tmp/ENV_VAR_LDS >> "$HOME/$BASH_PROFILE"
rm /tmp/ENV_VAR_LDS

source "$HOME/$BASH_PROFILE"

echo "Installed..." 
