#!/Users/dharmeshsingh/.virtualenvs/py3/bin/python

import argparse
import os
parser = argparse.ArgumentParser(description = "A utitlity app for creating files for programming languages")

parser.add_argument('-f','--file',action="store", dest="file_name")

parser.add_argument('-v','--with-vector',action='store_true', dest='include_vector',default=False)

parser.add_argument('-s','--with-string',action='store_true', dest='include_string',default=False)

parser.add_argument('-d','--without-defines',action='store_false',dest='include_defines',default=True)

parser.add_argument('-n','--no-run',action='store_true',dest='show_only',default=False);

args = parser.parse_args()
INCLUDES=[]
DEFINES=[]


#Default values for defines
DEFINES.append("ll long long int")
DEFINES.append("ull unsigned long long int") 


if "cpp" in args.file_name:
	INCLUDES.append("<iostream>")

	if args.include_vector:
		INCLUDES.append("<vector>")
	if args.include_string:
		INCLUDES.append("<string>")


FILE = open(args.file_name,"w+")	

for i in INCLUDES:
	FILE.write("#include " + i + "\n")

if args.include_defines:
	for i in DEFINES:
		FILE.write("#define " + i + "\n")
if args.show_only:
	print("A file named \'"+args.file_name+" will be created with following data: ")
	line = FILE.readline()
	while line:
		print(line)
		line = FILE.readline()
	os.remove(args.file_name)
		


